In [92]:
!pip install gensim

In [93]:
import gensim
from gensim.models import Word2Vec,KeyedVectors
import gensim.downloader as api

In [94]:
wv=api.load('word2vec-google-news-300')
# wv=api.load('word2vec-google-news-300')


In [95]:
vec_king=wv['king']
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [96]:
import pandas as pd
message=pd.read_csv('SMSSpamCollection.txt',sep='\t',names=['label','message'])


In [97]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()
import re
from nltk.corpus import stopwords

In [98]:
corpus=[]
for i in range(len(message)):
    review=re.sub('[^a-zA-Z]'," ",message['message'][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review ]
    review=" ".join(review)
    corpus.append(review)

In [99]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [100]:
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess

In [101]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for word in sent_token:
        words.append(simple_preprocess(word))


In [102]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [103]:
import gensim


In [104]:
#train word2vec from scratch
model=gensim.models.Word2Vec(words)

In [105]:
model.wv.index_to_key

['to',
 'you',
 'the',
 'it',
 'and',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'will',
 'if',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'home',
 'she',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'hi',
 'phone',
 'they',
 'new',
 'please',
 'later',
 'pls',
 'any',
 'her',
 'ha',
 'co',
 'did',
 'been',
 'msg',
 'min',
 'some',
 'an',
 'night',
 'make',
 'dear',
 'who',
 'here',
 'message',
 'say',
 'well',
 'where',
 're',
 'thing',
 'much',
 'oh',

In [106]:
model.corpus_count

5569

In [107]:
model.epochs

5

In [108]:
model.wv.similar_by_word('good')

[('day', 0.9988088011741638),
 ('well', 0.9987131953239441),
 ('my', 0.9986562132835388),
 ('night', 0.9986075758934021),
 ('all', 0.9985572099685669),
 ('morning', 0.998555064201355),
 ('not', 0.9984475374221802),
 ('thing', 0.9984307289123535),
 ('dear', 0.998397171497345),
 ('where', 0.9983318448066711)]

In [109]:
model.wv['good']

array([-2.82384783e-01,  3.53972584e-01,  1.64426282e-01,  1.97359234e-01,
        1.09952115e-01, -6.65605485e-01,  2.44331777e-01,  6.76540077e-01,
       -4.07369494e-01, -1.78319216e-01, -1.76979437e-01, -5.67061782e-01,
        3.71801056e-04,  1.57555103e-01,  2.80087680e-01, -2.34452814e-01,
        1.80032149e-01, -4.03911412e-01, -2.42618304e-02, -7.92726040e-01,
        3.59852612e-01,  1.90419763e-01,  2.04240829e-01, -3.05385500e-01,
       -5.62094301e-02,  1.20485891e-02, -2.79271096e-01, -2.79610097e-01,
       -3.34319860e-01,  5.90165555e-02,  4.58634555e-01,  2.02572923e-02,
        1.65958434e-01, -2.51445711e-01, -1.45221859e-01,  5.83447456e-01,
        8.18479583e-02, -1.87172964e-01, -1.48375064e-01, -6.57908797e-01,
        1.96984202e-01, -3.84220868e-01, -2.36202791e-01,  3.37956361e-02,
        2.31186450e-01,  1.30359584e-03, -2.31549442e-01, -9.17999372e-02,
        2.69745797e-01,  1.65255234e-01,  2.98676878e-01, -2.84946978e-01,
       -1.08417720e-01,  

In [110]:
model.wv['good'].shape

(100,)

In [111]:
import numpy as np
def avg_word2Vec(doc):
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)
avg_word2Vec(words[0])

array([-0.18847093,  0.24134213,  0.12004878,  0.12697983,  0.08574069,
       -0.47759047,  0.16301781,  0.46261343, -0.27548492, -0.14512134,
       -0.12251008, -0.3835381 , -0.03765196,  0.11444677,  0.19369864,
       -0.14902887,  0.10414294, -0.2936538 , -0.0178681 , -0.5330565 ,
        0.20728043,  0.12120712,  0.12136707, -0.21908522, -0.03967704,
        0.0108279 , -0.2099059 , -0.18296395, -0.23542012,  0.04207741,
        0.2994293 ,  0.01853033,  0.0982224 , -0.17597304, -0.1057892 ,
        0.40109298,  0.08345897, -0.1358575 , -0.13805796, -0.45704308,
        0.12359361, -0.2538145 , -0.17605047,  0.01820579,  0.15698957,
       -0.01246953, -0.1442021 , -0.05510201,  0.20705083,  0.11762656,
        0.18556783, -0.20707758, -0.06425221,  0.07003842, -0.11353993,
        0.06374326,  0.14845285, -0.02513602, -0.41983256,  0.13485608,
       -0.00281693,  0.160057  ,  0.00713946, -0.08562572, -0.30517998,
        0.29613355,  0.07912119,  0.23438716, -0.337478  ,  0.39

TQDM is a python library through which progress bars can be added to for loops to show their status. Whenever there was a time taking loop with lots of iterations we use a variable, increment it in each iteration and print its status to know the status of the loop. This is where tqdm comes in.

In [112]:
from tqdm import tqdm

In [113]:
x=[]
for i in tqdm(range(len(words))):
    x.append(avg_word2Vec(words[i]))

100%|██████████| 5569/5569 [00:00<00:00, 12541.30it/s]


In [114]:
x

[array([-0.18847093,  0.24134213,  0.12004878,  0.12697983,  0.08574069,
        -0.47759047,  0.16301781,  0.46261343, -0.27548492, -0.14512134,
        -0.12251008, -0.3835381 , -0.03765196,  0.11444677,  0.19369864,
        -0.14902887,  0.10414294, -0.2936538 , -0.0178681 , -0.5330565 ,
         0.20728043,  0.12120712,  0.12136707, -0.21908522, -0.03967704,
         0.0108279 , -0.2099059 , -0.18296395, -0.23542012,  0.04207741,
         0.2994293 ,  0.01853033,  0.0982224 , -0.17597304, -0.1057892 ,
         0.40109298,  0.08345897, -0.1358575 , -0.13805796, -0.45704308,
         0.12359361, -0.2538145 , -0.17605047,  0.01820579,  0.15698957,
        -0.01246953, -0.1442021 , -0.05510201,  0.20705083,  0.11762656,
         0.18556783, -0.20707758, -0.06425221,  0.07003842, -0.11353993,
         0.06374326,  0.14845285, -0.02513602, -0.41983256,  0.13485608,
        -0.00281693,  0.160057  ,  0.00713946, -0.08562572, -0.30517998,
         0.29613355,  0.07912119,  0.23438716, -0.3

In [118]:
len(x)

5569

In [116]:
import warnings 
warnings.filterwarnings(action='ignore')

In [120]:
x=np.array(x,dtype='object')

In [126]:
y=pd.get_dummies(message['label'])['ham'].astype('int')

In [127]:
y

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: ham, Length: 5572, dtype: int32

In [129]:
x[0]

array([-0.18847093,  0.24134213,  0.12004878,  0.12697983,  0.08574069,
       -0.47759047,  0.16301781,  0.46261343, -0.27548492, -0.14512134,
       -0.12251008, -0.3835381 , -0.03765196,  0.11444677,  0.19369864,
       -0.14902887,  0.10414294, -0.2936538 , -0.0178681 , -0.5330565 ,
        0.20728043,  0.12120712,  0.12136707, -0.21908522, -0.03967704,
        0.0108279 , -0.2099059 , -0.18296395, -0.23542012,  0.04207741,
        0.2994293 ,  0.01853033,  0.0982224 , -0.17597304, -0.1057892 ,
        0.40109298,  0.08345897, -0.1358575 , -0.13805796, -0.45704308,
        0.12359361, -0.2538145 , -0.17605047,  0.01820579,  0.15698957,
       -0.01246953, -0.1442021 , -0.05510201,  0.20705083,  0.11762656,
        0.18556783, -0.20707758, -0.06425221,  0.07003842, -0.11353993,
        0.06374326,  0.14845285, -0.02513602, -0.41983256,  0.13485608,
       -0.00281693,  0.160057  ,  0.00713946, -0.08562572, -0.30517998,
        0.29613355,  0.07912119,  0.23438716, -0.337478  ,  0.39

In [139]:
dataframe=[]
for i in range(len(x)):
    dataframe.append(pd.DataFrame(x[i].reshape(1,-1)))
df=pd.concat(dataframe,ignore_index=True)

In [169]:
message.shape

(5572, 2)

(5569,)

In [165]:
y=message[list(map(lambda x:len(x)>0,corpus))]
y=pd.get_dummies(y['label'])
y=y.iloc[:,0].values


In [168]:
y.shape

(5569,)

In [166]:
df['target']=y

In [167]:
df.head()

0         1         2         3         4         5         6  \
0 -0.188471  0.241342  0.120049  0.126980  0.085741 -0.477590  0.163018   
1 -0.171659  0.211486  0.103304  0.109969  0.079971 -0.415550  0.128577   
2 -0.194159  0.258195  0.128076  0.147444  0.075932 -0.524312  0.162015   
3 -0.255441  0.325054  0.154807  0.172977  0.116641 -0.637079  0.209345   
4 -0.227205  0.268128  0.138733  0.145600  0.111476 -0.544562  0.176188   

          7         8         9  ...        91        92        93        94  \
0  0.462613 -0.275485 -0.145121  ...  0.183781  0.023013  0.061615  0.420558   
1  0.408673 -0.240087 -0.119668  ...  0.151463  0.013709  0.045691  0.357084   
2  0.453475 -0.289552 -0.180896  ...  0.194345  0.012412  0.040466  0.427854   
3  0.626235 -0.373427 -0.181681  ...  0.239123  0.026140  0.085633  0.553170   
4  0.540638 -0.323067 -0.163021  ...  0.204267  0.028075  0.075179  0.474911   

         95        96        97        98        99  target  
0  0.198710  0.158227 -0.187487  0.141484  0.024709    True  
1  0.166458  0.137681 -0.171878  0.128557  0.014990    True  
2  0.185900  0.107989 -0.219566  0.166734  0.038569   False  
3  0.266121  0.225270 -0.256370  0.191027  0.026464    True  
4  0.234201  0.185697 -0.229144  0.156931  0.024432    True  

[5 rows x 101 columns]

preprocessing

In [155]:
df.describe()

0            1            2            3            4  \
count  5557.000000  5557.000000  5557.000000  5557.000000  5557.000000   
mean     -0.222489     0.284697     0.142901     0.150113     0.100277   
std       0.041692     0.045584     0.021994     0.021284     0.031203   
min      -0.348044     0.035010     0.003776     0.014250    -0.363093   
25%      -0.247714     0.261204     0.130979     0.139008     0.090638   
50%      -0.228149     0.285942     0.144000     0.151988     0.103952   
75%      -0.204370     0.307507     0.155549     0.163166     0.116533   
max       0.235635     0.748492     0.310603     0.255103     0.189744   

                 5            6            7            8            9  ...  \
count  5557.000000  5557.000000  5557.000000  5557.000000  5557.000000  ...   
mean     -0.561234     0.187366     0.540765    -0.324757    -0.175796  ...   
std       0.077791     0.038378     0.077687     0.045827     0.030011  ...   
min      -0.830448     0.022356     0.044382    -0.458843    -0.399762  ...   
25%      -0.610656     0.170178     0.497843    -0.354532    -0.192451  ...   
50%      -0.569393     0.185750     0.547390    -0.330120    -0.175805  ...   
75%      -0.520860     0.200648     0.591172    -0.299997    -0.159523  ...   
max      -0.044385     0.727456     0.746652    -0.028436    -0.010705  ...   

                91           92           93           94           95  \
count  5557.000000  5557.000000  5557.000000  5557.000000  5557.000000   
mean      0.216036     0.029781     0.071845     0.486463     0.234604   
std       0.032602     0.023668     0.022194     0.068500     0.036475   
min       0.021937    -0.013114     0.005345     0.034528     0.022923   
25%       0.199235     0.020775     0.060325     0.450033     0.214604   
50%       0.218306     0.027017     0.071852     0.493297     0.236899   
75%       0.234768     0.032888     0.081122     0.530133     0.258868   
max       0.471177     0.442182     0.368410     0.770334     0.346464   

                96           97           98           99       target  
count  5557.000000  5557.000000  5557.000000  5557.000000  5569.000000  
mean      0.180601    -0.219870     0.161458     0.026310     0.865865  
std       0.039474     0.045043     0.023674     0.017590     0.340828  
min       0.013043    -0.348225     0.008728    -0.270026     0.000000  
25%       0.157579    -0.245298     0.148864     0.023468     1.000000  
50%       0.183363    -0.226380     0.162661     0.028181     1.000000  
75%       0.204192    -0.203911     0.176329     0.033159     1.000000  
max       0.508795     0.358325     0.261240     0.079442     1.000000  

[8 rows x 101 columns]

In [157]:
df.dtypes

0         float32
1         float32
2         float32
3         float32
4         float32
           ...   
96        float32
97        float32
98        float32
99        float32
target      int32
Length: 101, dtype: object

In [145]:
df.isnull().sum()

0         12
1         12
2         12
3         12
4         12
          ..
96        12
97        12
98        12
99        12
target     0
Length: 101, dtype: int64

In [172]:
df.dropna(inplace=True)

In [173]:
df.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
target    0
Length: 101, dtype: int64

In [176]:
x=df.drop(['target'],axis=1)

In [177]:
x

0         1         2         3         4         5         6   \
0    -0.188471  0.241342  0.120049  0.126980  0.085741 -0.477590  0.163018   
1    -0.171659  0.211486  0.103304  0.109969  0.079971 -0.415550  0.128577   
2    -0.194159  0.258195  0.128076  0.147444  0.075932 -0.524312  0.162015   
3    -0.255441  0.325054  0.154807  0.172977  0.116641 -0.637079  0.209345   
4    -0.227205  0.268128  0.138733  0.145600  0.111476 -0.544562  0.176188   
...        ...       ...       ...       ...       ...       ...       ...   
5564 -0.216274  0.296054  0.158881  0.167147  0.092790 -0.580615  0.197662   
5565 -0.228222  0.283398  0.140613  0.160538  0.106368 -0.583190  0.190624   
5566 -0.258139  0.331436  0.159758  0.165307  0.108491 -0.636953  0.221255   
5567 -0.232621  0.292083  0.143063  0.157356  0.104010 -0.581191  0.190529   
5568 -0.264551  0.306881  0.153668  0.169128  0.123818 -0.632108  0.197150   

            7         8         9   ...        90        91        92  \
0     0.462613 -0.275485 -0.145121  ...  0.349600  0.183781  0.023013   
1     0.408673 -0.240087 -0.119668  ...  0.312058  0.151463  0.013709   
2     0.453475 -0.289552 -0.180896  ...  0.348170  0.194345  0.012412   
3     0.626235 -0.373427 -0.181681  ...  0.472762  0.239123  0.026140   
4     0.540638 -0.323067 -0.163021  ...  0.410485  0.204267  0.028075   
...        ...       ...       ...  ...       ...       ...       ...   
5564  0.526750 -0.330596 -0.194617  ...  0.403732  0.223916  0.027297   
5565  0.558969 -0.343514 -0.173077  ...  0.425974  0.227191  0.015868   
5566  0.621285 -0.370433 -0.197260  ...  0.468779  0.255035  0.038286   
5567  0.556443 -0.333834 -0.182924  ...  0.418275  0.224389  0.033234   
5568  0.612382 -0.362627 -0.192507  ...  0.459644  0.236190  0.029271   

            93        94        95        96        97        98        99  
0     0.061615  0.420558  0.198710  0.158227 -0.187487  0.141484  0.024709  
1     0.045691  0.357084  0.166458  0.137681 -0.171878  0.128557  0.014990  
2     0.040466  0.427854  0.185900  0.107989 -0.219566  0.166734  0.038569  
3     0.085633  0.553170  0.266121  0.225270 -0.256370  0.191027  0.026464  
4     0.075179  0.474911  0.234201  0.185697 -0.229144  0.156931  0.024432  
...        ...       ...       ...       ...       ...       ...       ...  
5564  0.055862  0.496794  0.221703  0.142248 -0.235216  0.179940  0.044628  
5565  0.067864  0.507363  0.237668  0.172911 -0.242174  0.175489  0.033366  
5566  0.092740  0.562183  0.272684  0.226523 -0.239322  0.183536  0.028662  
5567  0.076214  0.506414  0.243646  0.183606 -0.228200  0.166783  0.023622  
5568  0.078686  0.550252  0.272691  0.202802 -0.259013  0.177705  0.029774  

[5557 rows x 100 columns]

In [178]:
y=df['target']

In [179]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [185]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(x_train,y_train)

RandomForestClassifier()

In [187]:
from sklearn.metrics import classification_report,accuracy_score
y_pred=classifier.predict(x_test)
accuracy_score(y_pred,y_test)

0.9719424460431655

In [189]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.89      0.90      0.89       183
        True       0.98      0.98      0.98      1207

    accuracy                           0.97      1390
   macro avg       0.94      0.94      0.94      1390
weighted avg       0.97      0.97      0.97      1390

